name: project_es
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: 3.0.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  firebase_storage: ^11.2.5
  cached_network_image: 3.3.1
  collection: 1.18.0
  flutter_animate: ^4.5.0
  flutter_cache_manager: 3.3.1
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  go_router: ^13.2.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_path: ^0.7.1
  page_transition: 2.1.0
  path_provider: ^2.1.3
  path_provider_android: ^2.2.4
  path_provider_foundation: ^2.3.2
  path_provider_platform_interface: ^2.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shared_preferences_android: ^2.2.2
  shared_preferences_foundation: ^2.3.5
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.3.0
  sqflite: ^2.3.3
  timeago: ^3.6.1
  url_launcher: ^6.2.6
  url_launcher_android: ^6.3.1
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2
  cloud_firestore: ^4.16.1
  google_maps_flutter: ^2.6.0
  location: ^5.0.0
  flutter_polyline_points: ^2.0.0


dev_dependencies:
  flutter_lints: ^3.0.2
  lints: 3.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

