// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // api key google maps AIzaSyA3BgAJBN8DFofqxJJMm56jeo8NOvedp1Q
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYgDRhYEyRF0fotYO2O1JxysQR4XEwUB0',
    appId: '1:664321592260:android:2407e5def7394163de7291',
    messagingSenderId: '664321592260',
    projectId: 'flutter-chat-app-ef56b',
    storageBucket: 'flutter-chat-app-ef56b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANnx-liLFuiGSGd4et96TpK1hZ3ZTzsSw',
    appId: '1:664321592260:ios:aae1fb205db90d50de7291',
    messagingSenderId: '664321592260',
    projectId: 'flutter-chat-app-ef56b',
    storageBucket: 'flutter-chat-app-ef56b.appspot.com',
    iosClientId: '664321592260-mbuk8i8a3dbk8au5bn0llm34eckel8ge.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
