# Define a versão mínima do iOS
platform :ios, '15.0'

# CocoaPods analytics envia estatísticas de rede sincronamente afetando a latência do build do Flutter.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Define o projeto e suas configurações
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} deve existir. Se você está executando pod install manualmente, certifique-se de que flutter pub get seja executado primeiro"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT não encontrado em #{generated_xcode_build_settings_path}. Tente deletar Generated.xcconfig, depois execute flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Adicionar pod Google Maps com versão compatível
  pod 'GoogleMaps', '>= 8.4', '< 9.0'
  pod 'Google-Maps-iOS-Utils', '~> 3.10.3'

  # Adicionar pods do Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # Resolver problemas com o Firebase
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end