@startuml

class User {
    - userID: Integer
    - email: String
    - password: String
    - name: String
    /'
    + login(email: String, password: String): boolean
    + logout(): void
    + updateProfile(name: String, email: String): void
    '/
}

class Location {
    - name: String
    - latitude: Double
    - longitude: Double
    /'
    + getName(): String
    + getLatitude(): Double
    + getLongitude(): Double
    '/
}

class WaterReport {
    - location: String
    - date: Date
    - tip: String
    /'
    + getLocation(): Location
    + getDate(): Date
    + getTip(): String
    + getParameters(): List<Parameter>
    '/
}

class Parameter {
    - name: String
    - value: Double
    - unit: String
    /'
    + getName(): String
    + getValue(): Double
    + getColor(): Color
    + getUnit(): String
    '/
}

enum Color {
    GREEN
    YELLOW
    RED
    BROWN
}

class Map {
}

class Pin {
    - pinID: Integer
    /'
    + getLatitude(): Double
    + getLongitude(): Double
    + getWaterReport(): WaterReport
    '/
}

User "1" *-- "1" Location
WaterReport "1" *-- "9" Parameter
Parameter "1" -- "1" Color
Map "1" -- "1..*" Pin
Pin "1" *-- "1" WaterReport
Pin "1" -- "1" Location
Location "1" *-- "1" WaterReport
Pin "1" -- "1" Color

@enduml
